#!/bin/sh

#SBATCH --partition=p_ak1833_1
#SBATCH --job-name=karyotyping
#SBATCH --time=5-00:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=20
#SBATCH --mem=100G
#SBATCH --output=./karyotyping.log.%j
#SBATCH --error=./karyotyping.err.%j
#SBATCH --mail-user=jiayiliujiayiliu@gmail.com
#SBATCH --mail-type=ALL


# load singularity module
module purge

module load singularity/3.8.3
# Create temporary directory to be populated with directories to bind-mount in the container
# where writable file systems are necessary. Adjust path as appropriate for your computing environment.
workdir=$(python -c 'import tempfile; print(tempfile.mkdtemp())')

mkdir -p -m 700 ${workdir}/run ${workdir}/tmp ${workdir}/var/lib/conpyter
cat > ${workdir}/conpyter.conf <<END
provider=sqlite
END

export SINGULARITY_BIND="/home/jl2791,/scratch/jl2791,/projectsp,/projects,/cache"

# port
readonly PORT=$(python -c 'import socket; s=socket.socket(); s.bind(("", 0)); print(s.getsockname()[1]); s.close()')


singularity exec \
/home/jl2791/container/conpyterlab0.2.sif \
bash -c \
"source /opt/conda/etc/profile.d/conda.sh && conda activate alcohol && Rscript ./eSNP-Karyotype.r --bamdir ./00.raw"

#bash -c \
#"source /opt/conda/etc/profile.d/conda.sh && conda activate alcohol && Rscript ./eSNP-Karyotype.r --bamdir ./00.raw > /dev/null 2>&1"
